name: PR Close

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  destroy-preview-environment:
    name: Destroy Preview Environment
    runs-on: ubuntu-latest
    env:
      tfcWorkspaceName: nextra-docs-${{ github.event.number }}
      tfcOrg: jhutchinson531
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.3
        with:
          terraform_version: 1.5.1
          cli_config_credentials_token: ${{ secrets.TFC_API_TOKEN }}

      - name: Initialize Terraform Workspace
        id: init-workspace
        run: |
          echo "Initializing Terraform workspace: $tfcWorkspaceName"

          sed -i 's/name = "nextra-docs"/name = "'$tfcWorkspaceName'"/' main.tf
          terraform init -input=false

      - name: Destroy preview environment
        id: destroy-preview-environment
        run: |
          terraform destroy --auto-approve

          curl \
            --header "Authorization: Bearer ${{ secrets.TFC_API_TOKEN }}" \
            --header "Content-Type: application/vnd.api+json" \
            --request DELETE \
            "https://app.terraform.io/api/v2/organizations/${tfcOrg}/workspaces/${tfcWorkspaceName}"
