name: PR Validate

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

permissions:
  pull-requests: write

jobs:
  deploy-preview-environment:
    name: Deploy Preview Environment
    runs-on: ubuntu-latest
    env:
      tfcWorkspaceName: nextra-docs-${{ github.event.number }}
      tfcOrg: jhutchinson531
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.3
        with:
          terraform_version: 1.5.1
          terraform_wrapper: false
          cli_config_credentials_token: ${{ secrets.TFC_API_TOKEN }}

      - name: Initialize Terraform Workspace
        id: init-workspace
        run: |
          echo "Initializing Terraform workspace: $tfcWorkspaceName"

          sed -i 's/name = "nextra-docs"/name = "'$tfcWorkspaceName'"/' main.tf
          terraform init -input=false

      - name: Build and deploy preview environment
        id: build-deploy-preview-environment
        run: |
          terraform apply --auto-approve -var is_prod=${{ vars.IS_VERCEL_PROD }}

      - name: Terraform Output
        run: |
          terraform output
        continue-on-error: true

      - name: Get Preview URL
        id: get-preview-url
        run: |
          PREVIEW_DOMAIN=$(terraform output -raw preview_domain)
          PREVIEW_URL="https://$PREVIEW_DOMAIN"

          echo Preview environment deployed at: $PREVIEW_URL
          echo "preview-url=$PREVIEW_URL" >> $GITHUB_OUTPUT

      - name: Find Comment if Exists
        uses: peter-evans/find-comment@v2.4.0
        id: find-comment
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: Preview Environment Deployed

      - name: Post Comment with Preview URL
        uses: peter-evans/create-or-update-comment@v3.0.2
        with:
          comment-id: ${{ steps.find-comment.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            #### Preview Environment Deployed 🖌

            Visit the preview at: ${{ steps.get-preview-url.outputs.preview-url }}
          edit-mode: replace
