name: Release

on:
  push:
    branches:
      - main

jobs:
  deploy-production-environment:
    name: Deploy Production Environment
    runs-on: ubuntu-latest
    env:
      tfcWorkspaceName: nextra-docs
      tfcOrg: jhutchinson531
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.3
        with:
          terraform_version: 1.5.1
          cli_config_credentials_token: ${{ secrets.TFC_API_TOKEN }}

      - name: Terraform Init, create TFC workspace
        id: init-workspace
        run: |
          terraform init -input=false

      - name: Build and deploy pproduction environment
        id: build-deploy-production-environment
        run: |
          terraform apply --auto-approve -var is_prod=true

      - name: Terraform Output
        id: output
        run: |
          terraform output -no-color
        continue-on-error: true
